### PR TITLE
Add aws production webworkers

### PR DESCRIPTION
**Pull request by dannyroberts**

### CODE REVIEW

**Comment by dannyroberts** [comment]
`inventory.ini.j2` is a template that generates `inventory.ini`, and the context comes at least in part from api requests made to aws itself to get machine IP addresses. It's a stepping stone to something more automated hopefully, but even as it is, it's saved me a lot of time and human error copy-pasting IP addresses from the UI or something as I create a bunch of new machines at a time.

**Comment by millerdev** [comment]
@dannyroberts is safe to roll this back (even though https://github.com/dimagi/commcare-cloud/pull/2271 has been rolled in)?

**Comment by dannyroberts** [comment]
I think the easiest way to "roll this back" is to just remove web{0..5} from [webworkers] in inventory.ini.j2 and inventory.ini

**Comment by pr33thi** [comment]
Just to clarify, the prod webworkers are currently on AWS?

**Comment by dannyroberts** [comment]
We now have some on rackspace and some on AWS. This was done while firefighting general slowness (but it's also nice that it's a step in the right direction for the AWS migration as well).

**Pull request merged**
