### PR TITLE
Ns/icds new backup request

### PR DESCRIPTION
**Pull request by NitigyaS**
Added Postgresql nodes in netvault . Because we do not have all standby running.

### CODE REVIEW

**Comment by snopoke** [comment]
Don't you think we should setup standby nodes?

**Comment by NitigyaS** [comment]
Yes, I think we should.  NIC is not taking backups of all shards as of now and for those that they are doing that's only half / corrupted backup. Do we have enough storage to provision standbys for all shards?

**Comment by snopoke** [comment]
Yes we should if we delete the old couch and PG nodes

**Comment by NitigyaS** [comment]
Closing since I have setup Standbys.

**Pull request closed without merging**
