### PR TITLE
importing replica to tfstate and switching formplayer db url to new fp db

### PR DESCRIPTION
**Pull request by prem-fissionhq**
https://dimagi-dev.atlassian.net/browse/SAAS-11828

separating Formplayer database to separate RDS instance and configuring formplayer DB URL to point new pgformplayer0-staging database host.

##### ENVIRONMENTS AFFECTED

Staging

### CODE REVIEW

**Comment by prem-fissionhq** [comment]
@shyamkumarlchauhan facing an issue in modifying the DB subnet group of the new standalone instance, can you please help?

image

**Comment by shyamkumarlchauhan** [comment]
> @shyamkumarlchauhan facing an issue in modifying the DB subnet group of the new standalone instance, can you please help?
> 
> image

As discussed this is resolved by  following  https://serverfault.com/questions/816820/aws-can-not-change-db-subnet-group-for-aws-rds

**Comment by prem-fissionhq** [comment]
thanks Shyam. Now, facing another error with terraform apply. Though the enhanced monitoring is not enabled the terraform is showing it as enabled. working on it.

**Comment by prem-fissionhq** [comment]
The monitoring_interval was set to 60 by default in src/commcare_cloud/commands/terraform/templates/postgresql.tf.j2 file. 
In order to disable it for staging. I have added monitoring_interval:0 into terraform.yml and pushed my changes. 

We still have to disable the `enabled_cloudwatch_log_exports` which is enabled by default to collect ['PostgreSQL', 'upgrade'] logs to cloudwatch. Please review my PR and let me know if they also have to be disabled. thanks.

**Comment by prem-fissionhq** [comment]
@shyamkumarlchauhan all issues have been fixed now., Please review my PR. thanks.

**Review by shyamkumarlchauhan — APPROVED** [review]

**Review by dannyroberts — APPROVED** [review]

**Comment by dannyroberts** [comment]
Awesome!

**Pull request merged**
