### PR TITLE
Reduce concurrency of few workers.

### PR DESCRIPTION
**Pull request by NitigyaS**
I have halved the concurrency for SoftLayer.  But looking for some suggestions on what would be a good number.

### CODE REVIEW

**Comment by snopoke** [comment]
Is this because the CPU usage is too high or because we don't need that many workers?

**Comment by NitigyaS** [comment]
CPU usage is normal. RAM usage is much higher.

**Comment by NitigyaS** [comment]
@snopoke can you review this.

**Comment by NitigyaS** [comment]
@gcapalbo Can you suggest which queues I can consolidate together. Do not want to club 2 high task processing queues together.

**Comment by gcapalbo** [comment]
@NitigyaS for now you could try putting the `email_queue` with the `celery,export_download_queue`, and putting the `ucr_queue` and `ucr_indicator_queue` together

**Pull request merged**
