### PR TITLE
Upgrade redis to V5

### PR DESCRIPTION
**Pull request by rohit-dimagi**
##### SUMMARY

Upgrade Redis to V5.0.8
https://redislabs.com/community/whats-new-redis-5/

##### ENVIRONMENTS AFFECTED

* INDIA
##### ISSUE TYPE

- Change Pull Request

### CODE REVIEW

**Comment by rohit-dimagi** [comment]
> What's driving for this change?

It's from TCl vulnerability mitigation https://docs.google.com/spreadsheets/d/1Wz5rSX6tX4aEL5EOBhe3lJvNvaWcB0lrnY7ghwdW_Mw/
> Also, I don't think we should continue to use India as a 'test' environment.

staging ?

**Comment by snopoke** [comment]
What about staging on TCL?

**Comment by rohit-dimagi** [comment]
> What about staging on TCL?

it will take atleast 2 week before that env is functional. i'll put this on backlog until then.

**Comment by rohit-dimagi** [comment]
Redis 6 is out, will work on that instead.

**Pull request closed without merging**
