### PR TITLE
Update ansible to 2.9

### PR DESCRIPTION
**Pull request by rohit-dimagi**
##### SUMMARY

* Update ansible to 2.9
* ~Update requirements to include roles and collections~

##### ENVIRONMENTS AFFECTED

* ALL
##### ISSUE TYPE

- Change Pull Request

### CODE REVIEW

**Comment by rohit-dimagi** [comment]
Moved collection part here https://github.com/dimagi/commcare-cloud/pull/3583

**Comment by rohit-dimagi** [comment]
The Porting https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.9.html seemed fine to do the upgrade. however after upgrade i noticed error almost immediately
1. ssh arg problem(Now merge)
2. Logging problem(https://github.com/ansible/ansible/pull/65582) 
3. seems vault is broken too( getting wrong sudo password error)

we probably should wait longer i guess.

**Comment by rohit-dimagi** [comment]
Upgrading to 2.9.4(Latest release). it has fixed the logging and vault problem.

**Comment by rohit-dimagi** [comment]
Still can't figure out why the build is failing.

**Comment by rohit-dimagi** [comment]
i have been running on 2.9.4 for quite some time and haven't faced any issue so far. i think it's safe to merge it. @dannyroberts  @snopoke  thoughts ?

**Comment by snopoke** [comment]
I think it's safe

**Pull request merged**
