### PR TITLE
Replace pgbouncer2- with pgbouncer3-production

### PR DESCRIPTION
**Pull request by dannyroberts**
##### ENVIRONMENTS AFFECTED
production

### CODE REVIEW

**Comment by dannyroberts** [comment]
Following https://dimagi.github.io/commcare-cloud/services/postgresql/migrating_plproxy.html to roll it out

**Comment by dannyroberts** [comment]
Yeah I think I should. I'll add that (remove pgbouncer2) before merging

**Comment by dannyroberts** [comment]
Actually I'm going to do that in a different PR that I merge after the next time we restart formplayer and active connections (https://app.datadoghq.com/dashboard/unt-6cf-nbs/postgres---overview?from_ts=1594668866477&fullscreen_section=overview&fullscreen_widget=256956003&live=true&to_ts=1594683266477&tpl_var_exclusions=pg_standby&fullscreen_start_ts=1594669066155&fullscreen_end_ts=1594683466155&fullscreen_paused=false) has gone down to zero. In the meantime I'll leave it there but not part of our inventory for processes that are still running (formplayer, celery processes waiting to finish tasks)

**Comment by dannyroberts** [comment]
https://github.com/dimagi/commcare-cloud/pull/3975

**Comment by orangejenny** [comment]
@dannyroberts thanks for the explanation

**Pull request merged**
