### PR TITLE
Adding Citusdb Machines of VMware in inventory

### PR DESCRIPTION
**Pull request by rohit-dimagi**
##### SUMMARY

* Adding Citusdb Machines of VMware in inventory

##### ENVIRONMENTS AFFECTED

* ICDS
##### ISSUE TYPE

- Change Pull Request

### CODE REVIEW

**Comment by rohit-dimagi** [comment]
I'm doing the initial set up here. After that someone needs to take over for the migration, Maybe @calellowitz

**Comment by rohit-dimagi** [comment]
@snopoke  Can you check why the build is failing ? i'm not familiar with error it's giving.

**Comment by snopoke** [comment]
Not sure why it's failing. I've seen that on a few PRs and wasn't able to get it past that point. Also tested locally but can't repro. @dannyroberts any thought's on why the build is hanging? It appears that neither of the background jobs are exiting. I don't see the following output:
```
[1]-  Done                    COMMCARE= pip install pip --upgrade
[2]+  Done                    COMMCARE= manage-commcare-cloud install
```

**Comment by snopoke** [comment]
@rohit-dimagi I think you can merge this though. I ran the unit tests locally:
```
nosetests -v
```

**Pull request merged**
