### PR TITLE
Creating purge EFS-mount directory temp files - cron jobs

### PR DESCRIPTION
**Pull request by rameshganne**
Creating purge EFS-mount directory temp files - cron jobs

ref: SAAS-11945

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
Is this code mostly copy-pasted from the other shared_dir task file? If so I'm wondering if there's a way to get the two to share the same code instead somehow

**Comment by rameshganne** [comment]
> Is this code mostly copy-pasted from the other shared_dir task file? If so I'm wondering if there's a way to get the two to share the same code instead somehow

**Comment by rameshganne** [comment]
> Is this code mostly copy-pasted from the other shared_dir task file? If so I'm wondering if there's a way to get the two to share the same code instead somehow

Yes, @dannyroberts. I had created the `src/commcare_cloud/ansible/roles/shared_dir/tasks/efs_mount_purge_old_files.yml`  file from the `commcare-cloud/src/commcare_cloud/ansible/roles/shared_dir/tasks/setup_host.yml` file. I had tried to execute the `- name: Create purging cron jobs` task without creating `efs_mount_purge_old_files.yml` by using tags & `import_tasks:setup_host.yml` but I could not fix it without a new file(efs_mount_purge_old_files.yml) that time. 

I verify it again to re-use the setup_host.yml file for the `- name: Create purging cron jobs` task.

**Comment by rameshganne** [comment]
I have included cron-job task in playbook[deploy_efs_mount_shared_dir.yml] by removing import_task utilities module.

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
