### PR TITLE
add SES/SNS configuration for swiss

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAAS-11172

##### ENVIRONMENTS AFFECTED
updates swiss's local settings to add the SES -> SNS email event config

### CODE REVIEW

**Comment by dannyroberts** [comment]
Is swiss already using SES for email? I forget

**Comment by biyeun** [comment]
@dannyroberts for checking bounced emails, yes

**Comment by dannyroberts** [comment]
Oops, looks like we forgot to merge this. @biyeun can you merge master / re-apply the vault change? Promise I'll merge this time

**Comment by biyeun** [comment]
@dannyroberts reopened here https://github.com/dimagi/commcare-cloud/pull/4154

**Pull request closed without merging**
