### PR TITLE
Nic cleanup

### PR DESCRIPTION
**Pull request by czue**
##### SUMMARY

Reconcile NIC inventory file with what exists today.

##### ENVIRONMENTS AFFECTED

Legacy NIC environment

##### ISSUE TYPE

- Change Pull Request

##### COMPONENT NAME

n/a

##### ADDITIONAL INFORMATION

not sure if the build will pass on this, but it makes it easier to run shell commands against NIC and not have to wade through a bunch of errors related to missing/dead servers

### CODE REVIEW

**Comment by mkangia** [comment]
There are three environments for icds as of now in repo,
Aren't two of those including icds-new obsolete?
@NitigyaS

**Comment by NitigyaS** [comment]
@mkangia `icds` and `icds-cas` are alias of same  and they point to new environement, `icds-new` is actually the older NIC one. 
this PR is for NIC's inventory modification.

**Comment by mkangia** [comment]
I would leave it to @NitigyaS for review since he has context on this and i think i need some more context on icds environments so i will offline with him.

**Comment by czue** [comment]
Yeah @mkangia this env is obsolete but since much of the infrastructure is still online and in use by the data team it's still useful to have up to date inventory.

**Comment by mkangia** [comment]
Thank @czue , i didn't know it was being used by the data team.

**Pull request merged**
