### PR TITLE
Firefighting training: add new formplayer machine

### PR DESCRIPTION
**Pull request by millerdev**
https://confluence.dimagi.com/display/internal/How+to+create+a+new+machine+in+an+AWS+environment

##### ENVIRONMENTS AFFECTED
staging

### CODE REVIEW

**Review by dannyroberts — APPROVED** [review]
Sorry, lost track. I assume it still best to merge this in?

**Comment by millerdev** [comment]
Sure, although I can't remember if I was ever successful in the end. Are you planning to decommission these training machines at some point?

**Comment by millerdev** [comment]
@dannyroberts is it easier to just delete the VM and close this PR?

**Comment by dannyroberts** [comment]
I think the idea was for us to remove one of the older machines of the same type so that the new work would be "real", but ours was the first one and it got cut short a little. I can just close this that's fine

**Pull request closed without merging**
