### PR TITLE
add formplayer debug options

### PR DESCRIPTION
**Pull request by calellowitz**
https://dimagi-dev.atlassian.net/browse/SAAS-10159
##### ENVIRONMENTS AFFECTED

Production

### CODE REVIEW

**Review by ctsims — APPROVED** [review]

**Comment by calellowitz** [comment]
@dannyroberts 
Looks like I broke the build with this, and I am not totally sure how. Any insight into those failures? It appears to be automatically generating an inventory file and comparing it to the real one, and they are now misaligned.

**Comment by dannyroberts** [comment]
yeah on aws saas envs we can't update inventory.ini directly, but you can update inventory.ini.j2 to have

```
[formplayer_c000:vars]
# your vars here
```
and then run `cchq production aws-fill-inventory --cached`. For more on that see https://confluence.dimagi.com/display/internal/Inventory+Management+for+AWS+Environments

**Comment by calellowitz** [comment]
Thanks Danny! I updated it to use the template, and refactored a bit to make it easier to add new machines.

**Review by dannyroberts — COMMENTED** [review]
nice, well done

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
