### PR TITLE
add health check interval to redis config

### PR DESCRIPTION
**Pull request by biyeun**
https://dimagi-dev.atlassian.net/browse/SAAS-11355 (and possibly the P2 that came up)

##### ENVIRONMENTS AFFECTED
all

### CODE REVIEW

**Comment by biyeun** [comment]
ok, looks like staging was fine with the change 👍

**Review by dannyroberts — APPROVED** [review]
Sounds you've put it up on staging and run check_services to make sure there are no errors? If so and clicking around on staging works then I think I'm good with the change

**Review by millerdev — APPROVED** [review]
I don't remember the issue we faced last time we rolled this out, but this seems fine as long as that scenario has been tested and is no longer a concern.

**Comment by dannyroberts** [comment]
We luckily _didn't_ roll it out last time, but when I was testing before rolling it out I found that when I ran `cchq staging update-config --limit django_manage` the `check_services` it runs after that failed, so I rolled back the config and raised the issue, which prompted the redis upgrade to 3.3.0

**Comment by biyeun** [comment]
@dannyroberts `check_services` runs at the end of `update-config` yeah? if so I didn't see any errors then. and also staging looks stable now that cal undid whatever he was working on

**Comment by dannyroberts** [comment]
Yup it does. This sounds good to roll out to me

**Pull request merged**
