### PR TITLE
adding chrony package for better time syncronization

### PR DESCRIPTION
**Pull request by prem-fissionhq**
https://dimagi-dev.atlassian.net/browse/SAAS-12195
##### ENVIRONMENTS AFFECTED

All

Applied on staging server as of now.

### CODE REVIEW

**Comment by dannyroberts** [comment]
Looks like this will mean both `chrony` and `ntp` are installed? Have you looked into what the docs say about having them both installed? Just want to make sure they're compatible and won't interfere with each other

**Comment by prem-fissionhq** [comment]
@dannyroberts We verified that chrony is uninstalling existing NTP package if it already installed so we thought of supporting both pacakges. Please let us know your suggestions. I think we can remove ntp from installing if not neccessary.  thanks

**Comment by dannyroberts** [comment]
OK I don't know enough of the details but I wanted to point out that `ntp` is installed in this same list (https://github.com/dimagi/commcare-cloud/pull/4805/files#diff-73416f28d12dc5cf4883b6343daca0dbefbf48502f82e43492db07f7c43becb2R59), which is at best redundant if `chrony` automatically uninstalls `ntp` (and at worst could interfere).

**Comment by prem-fissionhq** [comment]
@dannyroberts I have discussed again on this with Shyam and will use a var to control this installation. However, we are sure (tested) that chrony will uninstall the NTP while installing.

**Review by shyamkumarlchauhan — APPROVED** [review]

**Review by shyamkumarlchauhan — APPROVED** [review]

**Comment by prem-fissionhq** [comment]
@shyamkumarlchauhan can I use the same PR to apply changes on India or shall I apply after merging please let me know. thanks

**Review by shyamkumarlchauhan — APPROVED** [review]

**Comment by prem-fissionhq** [comment]
@shyamkumarlchauhan 
removing a task that verifies timesync server address in conf file as it is not required. The module lineinline updates the file only if not exist. 
Creating new task to install ntp package only when use_chrony is false. this is to avoid installation and uninstallation of chront and ntp packages.

**Review by shyamkumarlchauhan — APPROVED** [review]

**Comment by prem-fissionhq** [comment]
Applied on India Env.

**Review by dannyroberts — APPROVED** [review]

**Pull request merged**
