### PR TITLE
PR to remove old docs

### PR DESCRIPTION
**Pull request by sravfeyn**
Please see the background in the [google doc](https://docs.google.com/document/d/1kifgKiOQ-3ZCN4K-4h2N6K0B77MPDiqEfgvF65Tz5rs/edit#) This PR does following

- Adds a redirection message to index page and changelog pages.
- Adds a custom 404
- Removes all of the other files

Please don't merge, this is to be merged at a specific time

### CODE REVIEW

**Comment by sravfeyn** [comment]
@dannyroberts I might need your help on this to make sure the 404 is working correctly. In my local testing, all 404s went to the index page.

**Comment by dannyroberts** [comment]
Nice find. Could you PR the 404 page separately? That way we can verify that it's working the way we want before removing things

**Comment by dannyroberts** [comment]
Nice find. Could you PR the 404 page separately? That way we can verify that it's working the way we want before removing things

**Comment by sravfeyn** [comment]
https://github.com/dimagi/commcare-cloud/pull/5311/

@dannyroberts Is this good now?

**Comment by dannyroberts** [comment]
@sravfeyn I think to make the tests pass (and rightly so) you will have to remove the lines in `Makefile` that generate files for the old docs. But generally yeah, the links and better 404 page are helpful!

**Comment by sravfeyn** [comment]
@ctsims We are supposed to merge this today to kill the old docs at https://dimagi.github.io/commcare-cloud/ But Danny being offline there is no one to approve this PR, though his comments have been addressed. Is there any backstop on SaaS who can approve this?

**Comment by sravfeyn** [comment]
Yes, I have that in mind for future, since it doesn't affect anything user-facing for now.

**Review by millerdev — APPROVED** [review]

**Pull request merged**
