### PR TITLE
add caching at the proxy for app resource downloads

### PR DESCRIPTION
**Pull request by snopoke**
Add location and mappings to nginx config to cache app resources on the proxy. This is something we had set up for ICDS which protects the Django workers from multiple requests for the same resource.

##### ENVIRONMENTS AFFECTED
all

### CODE REVIEW

**Review by dannyroberts — COMMENTED** [review]
App downloads are still considered non-secret, right? My only comment here is that this would ignore any auth done at the django level for these routes in the future

**Review by calellowitz — APPROVED** [review]

**Comment by snopoke** [comment]
> App downloads are still considered non-secret, right? 

That's correct.

> My only comment here is that this would ignore any auth done at the django level for these routes in the future.

This is true. I don't believe there any current plans to support auth for these resources. Also any QA plan for that would likely fail with this enabled.

I'll put this on staging for now.

**Comment by snopoke** [comment]
Rolled out to staging. I can see the caching happening in the nginx logs.

**Comment by snopoke** [comment]
My main concern with this was Formplayer and whether the caching would impact live preview. I have confirmed that Formplayer does not use this endpoint to download apps, it uses the `api/download_ccz` endpoint. I have further confirmed that app preview and webapps work as expected with updating to released apps as well as live preview updating to the the latest version of the app.

**Comment by snopoke** [comment]
@dannyroberts any reason to hold off on rolling this out? We're hoping this will reduce the impact of a future Formplayer change that will force re-installation of all apps on formplayer machines.

**Review by dannyroberts — APPROVED** [review]
Nope, no reason to hold off. Looks good to me!

**Comment by snopoke** [comment]
I'll deploy on Monday

**Pull request merged**
