### PR TITLE
changed password to be different from india env

### PR DESCRIPTION
**Pull request by shyamkumarlchauhan**
Chaging password to different from india env. Below changes in vault file

set new AMQP password
removed s3 keys
set null values for bank account number ,ach,wire
set new couch user and password
set null values for dropbox
removed hubspot 
set airflow flask and secret
set datadog api and app keys
changed postgres user and passwords

##### ENVIRONMENTS AFFECTED
icds-staging

### CODE REVIEW

**Comment by snopoke** [comment]
some of the keys are invalid because they contain quotes:
```
AIRFLOW_FLASK_KEY
AMQP_PASSWORD
POSTGRES_USERS.devreadonly.password
POSTGRES_USERS.icds_testdata_writer.password  # I don't think we need this user at all
POSTGRES_USERS.icds_testdata_reader.password  # I don't think we need this user at all
POSTGRES_USERS.replication.password
COUCH_PASSWORD
```
You should test the config first.

Also I see a number of other keys that are the same:
```
ECRYPTFS_PASSWORD
FORMPLAYER_SENTRY_DSN
KSPLICE_ACTIVATION_KEY  # should be removed
FORMPLAYER_INTERNAL_AUTH_KEY
GMAPS_API_KEY  # should be removed
GOOGLE_ANALYTICS_API_ID  # should be removed
DRIFT_ID  # should be removed
KISSMETRICS_KEY  # should be removed
OPEN_EXCHANGE_RATES_API_ID  # should be removed
SECRET_KEY
SENTRY_DSN
SENTRY_API_KEY
STRIPE_PRIVATE_KEY  # should be removed
STRIPE_PUBLIC_KEY  # should be removed
SUMOLOGIC_URL   # should be removed
```

Finally - they vault file must be re-keyed with a new key so that we aren't reusing any vault keys.

**Comment by snopoke** [comment]
@shyamkumarlchauhan did you change the vault key?

**Comment by shyamkumarlchauhan** [comment]
> @shyamkumarlchauhan did you change the vault key?
 @snopoke yes the vault key was changed much earlier and it is different from india environment

**Comment by shyamkumarlchauhan** [comment]
> some of the keys are invalid because they contain quotes:
> 
> ```
> AIRFLOW_FLASK_KEY
> AMQP_PASSWORD
> POSTGRES_USERS.devreadonly.password
> POSTGRES_USERS.icds_testdata_writer.password  # I don't think we need this user at all
> POSTGRES_USERS.icds_testdata_reader.password  # I don't think we need this user at all
> POSTGRES_USERS.replication.password
> COUCH_PASSWORD
> ```
> 
> You should test the config first.
> 
> Also I see a number of other keys that are the same:
> 
> ```
> ECRYPTFS_PASSWORD
> FORMPLAYER_SENTRY_DSN
> KSPLICE_ACTIVATION_KEY  # should be removed
> FORMPLAYER_INTERNAL_AUTH_KEY
> GMAPS_API_KEY  # should be removed
> GOOGLE_ANALYTICS_API_ID  # should be removed
> DRIFT_ID  # should be removed
> KISSMETRICS_KEY  # should be removed
> OPEN_EXCHANGE_RATES_API_ID  # should be removed
> SECRET_KEY
> SENTRY_DSN
> SENTRY_API_KEY
> STRIPE_PRIVATE_KEY  # should be removed
> STRIPE_PUBLIC_KEY  # should be removed
> SUMOLOGIC_URL   # should be removed
> ```
> 
> Finally - they vault file must be re-keyed with a new key so that we aren't reusing any vault keys.

Testing done with updated vault file.
password where quotes has been mentioned has been changed to new passwords

**Pull request merged**
