### PR TITLE
increase plproxy connection limits

### PR DESCRIPTION
**Pull request by snopoke**
##### ENVIRONMENTS AFFECTED
ICDS

##### ISSUE TYPE
- Change Pull Request (will require short downtime to roll out)

### CODE REVIEW

**Comment by snopoke** [comment]
@rohit-dimagi can you handle rolling this out please. It's going to require a DB restart so we should schedule a small window of downtime (unless we can do it with just a reload)

**Comment by rohit-dimagi** [comment]
We can do with reload but looks complicated. https://www.postgresql.org/docs/current/sql-altersystem.html
i think rolling out during off hour should be fine.

**Comment by snopoke** [comment]
@rohit-dimagi I meant just doing a process reload instead of a restart `systemctl reload postgresql`

**Comment by rohit-dimagi** [comment]
Yeah the changed parameter requires a restart. The shared doc contains how to do it with reload.

**Pull request merged**
