### PR TITLE
Revert 2280 revert 2264 sr redis cluster

### PR DESCRIPTION
**Pull request by jmtroth0**
@sravfeyn @snopoke buddy: @Rohit25negi 

brings this (https://github.com/dimagi/commcare-cloud/pull/2264) back and adds the necessary application.properties line (I think). How can I test this besides just putting it on staging or spinning up a local cluster or something?

### CODE REVIEW

**Comment by sravfeyn** [comment]
We just need a deploy. I will do it

**Comment by jmtroth0** [comment]
Ok cool, but out of curiosity also, is there a way to test these jinja templates locally? Is there a playbook to generate a local version or something?

**Comment by sravfeyn** [comment]
I test these on the local virtualized [setup using vagrant.](https://github.com/dimagi/commcare-cloud/blob/master/src/commcare_cloud/ansible/README.md#local-vagrant-setup)

**Comment by jmtroth0** [comment]
Cool, if I wanted to avoid using vagrant, would that be possible?

**Pull request merged**
