### PR TITLE
Remove old blob deletion pillows

### PR DESCRIPTION
**Pull request by emord**
I thought I had already done this, but back in May I removed these from the HQ code https://github.com/dimagi/commcare-hq/pull/15972

### CODE REVIEW

**Comment by emord** [comment]
Now realize that this worked when deploying in fab because it generated these configs in the current code's directory. Going to merge to get rid of some erorrs after deploying #1424

**Comment by millerdev** [comment]
Are we no longer deleting unreferenced blobs? I think I'm changing my opinion on that, given the recent disk space issues we've had.

**Comment by emord** [comment]
@millerdev we haven't had those pillows running since May. I'm having difficulty finding any context as to why we deleted them but I recall talking about it with you at some point. If we want those to continue, we'd also need to revert the old HQ PR

**Comment by millerdev** [comment]
OK, thanks. I'll put this on my backlog to review.

**Pull request merged**
