### PR TITLE
Refuse to run terraform destroy

### PR DESCRIPTION
**Pull request by dannyroberts**
##### ENVIRONMENTS AFFECTED
saas envs

### CODE REVIEW

**Comment by dannyroberts** [comment]
@prem-fissionhq

**Comment by knguyen142** [comment]
What is the reasoning for not allowing a destroy?

**Comment by dannyroberts** [comment]
Just that it's a very destructive operation. If we ever ran it on production it would be a total disaster. It's an easy thing to change later and add a more flexible mechanism for preventing only unintended usage, but for now there's no time I can imagine needing to run this on staging, production, or india

**Review by knguyen142 — APPROVED** [review]

**Comment by prem-fissionhq** [comment]
Thanks Danny for implementing it so quickly 🙂

**Pull request merged**
