### PR TITLE
Add RAM on pgproxy0

### PR DESCRIPTION
**Pull request by millerdev**
@dannyroberts

### CODE REVIEW

**Comment by millerdev** [comment]
Do I need to schedule downtime for this or can it be deployed safely without that?

**Comment by dannyroberts** [comment]
Yeah resizing a machine unfortunately requires it stop and start, which takes a couple minutes. An alternative is to create another machine and replace all references to this one with references to that one, which of course doesn't work if there's data involved. While pgproxy maintains very little state compared to the actual partition dbs, it still seems like more trouble and risk than its worth to go that route, versus scheduling 2 minutes of downtime on during a low-load period.

**Comment by emord** [comment]
> While pgproxy maintains very little state compared to the actual partition dbs, it still seems like more trouble and risk than its worth to go that route, versus scheduling 2 minutes of downtime on during a low-load period

@dannyroberts Do you think its worth doing the no downtime deploy of this as practice of a useful workflow? 

from my understanding the only commcare "data" that plproxy contains are functions that are setup via configure_plproxy_cluster. is that correct?

**Comment by dannyroberts** [comment]
@emord Yeah, I think I agree with your suggestion now that you say it. I see the value in that.

**Comment by millerdev** [comment]
Did the no-downtime method: https://github.com/dimagi/commcare-cloud/pull/2585

I'm still getting familiar with new AWS automation, but my overall impression is that there were a lot of steps in the process. It was tedious and took a long time.

**Pull request closed without merging**
