### PR TITLE
Rollout logstash setup on prod and stag env

### PR DESCRIPTION
**Pull request by rohit-dimagi**
##### SUMMARY

* Rolling out Logstash on Prod and stg env

##### ENVIRONMENTS AFFECTED

* PROD
* STG
##### ISSUE TYPE

- Change Pull Request
In order to  upgrade datadog to V6. we need to import dogstream to logstash + filebeat setup.
It's already out on india and ICDS (https://github.com/dimagi/commcare-cloud/pull/3653).  
Since this rollout requires in metrics metadata changes it's better to rollout these on all env and then update the metadata setting.

### CODE REVIEW

**Comment by dannyroberts** [comment]
Hmm do you know what the error is about?

```
ERROR! the role 'sansible.java' was not found in /home/travis/build/dimagi/commcare-cloud/src/commcare_cloud/ansible/roles:/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/.ansible/roles:/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/.ansible/ansible_collections/dimagi/commcare_logstash/roles:/home/travis/build/dimagi/commcare-cloud/src/commcare_cloud/ansible
```

**Comment by snopoke** [comment]
It would appear that you can only specify other collections as dependencies for an Ansible Collection. So I think we'll have to add these dependencies to our requirements.yml file

**Comment by rohit-dimagi** [comment]
Added the deps and build is now passed.

**Comment by snopoke** [comment]
@rohit-dimagi what about `sansible.java`?

**Comment by rohit-dimagi** [comment]
Those deps are mentioned inside the `sansible.logstash` `meta` file so they are being pulled out fine.

**Comment by rohit-dimagi** [comment]
@dannyroberts  i can roll this out ?

**Comment by dannyroberts** [comment]
Yup sounds good!

**Pull request merged**
