### PR TITLE
Adding mobile web workers on ICDS environment

### PR DESCRIPTION
**Pull request by sanjay2916**
Adding mobile workers on ICDS environment

### CODE REVIEW

**Comment by snopoke** [comment]
Putting a hold on this since we're going to be migrating to VMWare soon.

**Comment by emord** [comment]
@snopoke were these requested to be decommissioned?

**Comment by emord** [comment]
@snopoke were these requested to be decommissioned?

**Comment by snopoke** [comment]
@emord no - we haven't requested decommissioning of these yet - I was going to wait until we had the others all set up

**Pull request closed without merging**
