### PR TITLE
install phonetic analysis plugin on prod

### PR DESCRIPTION
**Pull request by Robert-Costello**
https://dimagi-dev.atlassian.net/browse/USH-1700
##### ENVIRONMENTS AFFECTED

Production

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
This will install it on all environments next time they deploy ES, right?  I think that's fine.  Do we need to advise any manual steps to prevent that from breaking something?  My understanding is that it should just install the plugin, but it won't actually do anything until they migrate the index over.

**Comment by Robert-Costello** [comment]
>it should just install the plugin, but it won't actually do anything until they migrate the index over.

Yes, it should only install the plugin with no side effects or changes to functionality until settings and mapping are changed.

**Comment by snopoke** [comment]
> > it should just install the plugin, but it won't actually do anything until they migrate the index over.
> 
> Yes, it should only install the plugin with no side effects or changes to functionality until settings and mapping are changed.

Also, just to confirm that it won't restart ES either?

**Comment by Robert-Costello** [comment]
That's right it won't restart ES. The docs instruct you to restart each node after installation. I had to do that manually to make the plugin available locally and on staging we had run the command to deploy es to get a restart.

**Pull request merged**
