### PR TITLE
use g1 gc and string dedup for c014

### PR DESCRIPTION
**Pull request by calellowitz**
I had to manually change the `inventory.ini` file because I could not get the command to work, but I think I did so correctly 

##### ENVIRONMENTS AFFECTED

Production

### CODE REVIEW

**Review by millerdev — COMMENTED** [review]
> I could not get the command to work, but I think I did so correctly

I'm assuming by "the command" you mean `cchq production aws-fill-inventory --cached`

Travis thinks you didn't do it correctly
```
Hey, did you edit inventory.ini when you should have edited inventory.ini.j2?
That's a common cause of this test failure.
If so, make your change to inventory.ini.j2 and run
  cchq <env> aws-fill-inventory --cached
to fix this test
```

**Comment by dannyroberts** [comment]
This should fix the --cached thing: https://github.com/dimagi/commcare-cloud/pull/4389

**Comment by calellowitz** [comment]
Merged Danny's PR and kicked off the build again.

**Comment by calellowitz** [comment]
✅

**Review by dannyroberts — APPROVED** [review]

**Review by millerdev — APPROVED** [review]

**Pull request merged**
