### PR TITLE
Examples from H4 to H5

### PR DESCRIPTION
**Pull request by kaapstorm**
##### SUMMARY

nit: Corrected heading level for command examples in documentation.

##### ENVIRONMENTS AFFECTED

None.

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

N/A

##### ADDITIONAL INFORMATION

Commands are H4 headings. Their examples were also H4 headings, and so they appeared alongside them in the contents as if they were also commands. This change corrects that.

### CODE REVIEW

**Comment by dannyroberts** [comment]
This file is auto-generated, so you'll also have to edit the `make_docs` command, possibly just this line: https://github.com/dimagi/commcare-cloud/blob/14ec7abd7521f11bb0e6c6fbb6bd15ca9eb25794/src/commcare_cloud/manage_commcare_cloud/make_docs.py#L140

**Comment by kaapstorm** [comment]
How do I test the make-docs command?

**Comment by dannyroberts** [comment]
Oh sorry you can just run `make` locally—the script is triggered in the `Makefile` so that's all you have to do. If that's slow or you otherwise want to run it by itself, just look in the `Makefile` for the make-docs command

**Comment by kaapstorm** [comment]
Thanks. :+1: That worked.

**Pull request merged**
