### PR TITLE
add rkumar key

### PR DESCRIPTION
**Pull request by mkangia**
Add Rohit Kumar ssh key and user

already ran `update-users` from this branch to set things up

### CODE REVIEW

**Comment by mkangia** [comment]
Thanks @dannyroberts @sravfeyn

**Comment by sravfeyn** [comment]
Just to make sure, did you run this only on staging? Because I had to do it on all other envs for him.

**Comment by mkangia** [comment]
@sravfeyn thats correct. We did it only for onboarding session.
Sorry about that. I should have run it on all envs later. thanks for covering up here.

**Comment by sravfeyn** [comment]
Np! Wanted to confirm if there was a bug or something, thanks.

**Pull request merged**
