### PR TITLE
Add UAT domain to dedicated index

### PR DESCRIPTION
**Pull request by esoergel**
Add third BHA domain to the dedicated case search index, in the same vein as https://github.com/dimagi/commcare-cloud/pull/6308

https://dimagi.atlassian.net/browse/USH-4878

##### Environments Affected

Production

### CODE REVIEW

**Review by gherceg — COMMENTED** [review]
Do you have an idea of how much additional data is going to be included in the case_search_bha index?

**Comment by MartinRiese** [comment]
@gherceg if I ran a count query on the current index would that give you the answer you are looking for?

**Comment by MartinRiese** [comment]
@gherceg if I run the case search with out any other queries [here](https://www.commcarehq.org/a/co-carecoordination-uat/case/search/) I get 123435 hits. My understanding is that all those would end up in the bha index.

**Comment by gherceg** [comment]
Yeah that understanding is correct. For good measure I just did a `CaseSearchES().domain('co-carecoordination-uat').count()` and got the same result. This would increase the BHA index by ~25%. I checked current shard sizes for this index which are all below 1GB (there are 4 shards), so current storage on ES nodes is more than enough to accommodate this increase.

**Review by gherceg — APPROVED** [review]

**Pull request merged**
