### PR TITLE
Enable django security middleware on swiss and india

### PR DESCRIPTION
**Pull request by gherceg**
These changes have [been on staging](https://github.com/dimagi/commcare-cloud/pull/4279) for awhile now and should be safe to roll out. Will start with India and Swiss and then rollout to Production.
##### ENVIRONMENTS AFFECTED

India, Swiss

### CODE REVIEW

**Comment by gherceg** [comment]
@mjriley just wanted to make sure this doesn't conflict with any work you've done.

**Review by mjriley — APPROVED** [review]
Approving in that these changes don't break anything I'm doing. Not familiar with these settings, but I'd imagine staging exposed any issues?

**Review by dannyroberts — APPROVED** [review]

**Comment by gherceg** [comment]
@dannyroberts it looks like this change worked on india but not on swiss. Is there an extra step needed to have this change take effect on swiss besides a deploy?

**Comment by dannyroberts** [comment]
I think it would require `cchq <env> update-config` followed by a service restart (or deploy) in order to take affect. Not sure if that's what you meant; does that help?

**Comment by gherceg** [comment]
🤦 definitely knew that but forgot. Thanks!

**Pull request merged**
