### PR TITLE
Cs/add option to delete kafka

### PR DESCRIPTION
**Pull request by Charl1996**
TdH has recently experienced some odd issue where they couldn't run the `wipe_kafka.yml` playbook successfully, as the script tried to delete an internal topic (`__consumer_offsets`). As a result of this, we've thought it best to also include the option to reinstall kafka when running the playbook (the _"when your hammer is too small, use a bigger hammer"_ philosophy).

(After thinking about it, is it enough to just reinstall kafka? Should I also be removing Zookeeper, since Zookeeper is the one that actually [keeps track of the list of topics](https://www.cloudkarafka.com/blog/cloudkarafka-what-is-zookeeper.html#:~:text=Zookeeper%20keeps%20track%20of%20status%20of%20the%20Kafka%20cluster%20nodes%20and%20it%20also%20keeps%20track%20of%20Kafka%20topics%2C%20partitions%20etc)?)

##### ENVIRONMENTS AFFECTED
All (I guess)

### CODE REVIEW

**Review by snopoke — COMMENTED** [review]
why not just filter the topics being deleted to exclude internal ones?

**Comment by Charl1996** [comment]
@snopoke 

> why not just filter the topics being deleted to exclude internal ones?

That did came to mind, but won't that potentially create issues down the line, especially considering the `__consumer_topics`? I can imaging the chaos that could ensure when especially that topic still have some residual data.

**Comment by snopoke** [comment]
> @snopoke
> 
> > why not just filter the topics being deleted to exclude internal ones?
> 
> That did came to mind, but won't that potentially create issues down the line, especially considering the `__consumer_topics`? I can imaging the chaos that could ensure when especially that topic still have some residual data.

That topic is not important and does not impact our usage of Kafka so you can effectively ignore it. It is used by Kafka if you are using consumer groups.

**Comment by Charl1996** [comment]
@snopoke Sorry, I was actually referring to `__consumer_offsets` (not sure where I got `__consumer_topics` from). 
Am I correct in assuming that you are referring to `__consumer_offsets` and not my (probably made-up) `__consumer_topics` when you say we're not actually using it?

**Comment by snopoke** [comment]
> @snopoke Sorry, I was actually referring to `__consumer_offsets` (not sure where I got `__consumer_topics` from). Am I correct in assuming that you are referring to `__consumer_offsets` and not my (probably made-up) `__consumer_topics` when you say we're not actually using it?

Correct

**Comment by Charl1996** [comment]
Closing in favour of https://github.com/dimagi/commcare-cloud/pull/5386

**Pull request closed without merging**
