### PR TITLE
increase UCR pillow chunk size to 20 on pillow5

### PR DESCRIPTION
**Pull request by sravfeyn**
Thinking to roll this out and see if number of connections from pillow5 to ucr-main DB will reduce.

### CODE REVIEW

**Comment by snopoke** [comment]
If possible it would be good to change a pillow where there's another host with the same config so that we can compare.

**Comment by sravfeyn** [comment]
We will be able to compare with `pillow6` which has a default chunk size of 10.

**Comment by emord** [comment]
> Thinking to roll this out and see if number of connections from pillow5 to ucr-main DB will reduce.

Would the number of connections drop? From what I was thinking was we would see a higher rate of changes being processed (assuming that bulking saves is more efficient)

**Comment by sravfeyn** [comment]
That's true, if it is more efficient it would try to process more and open more connections, but unless it is efficient by a factor of 2 it won't open more connections than now. I think we can look at both the metrics (number of changes being processed and number of connections from pillow5) latter to see how it affects. 

We could also reduce `num_processes` if it becomes more efficient and opens more connections than desired.

**Comment by sravfeyn** [comment]
This needs https://github.com/dimagi/commcare-hq/pull/23182

**Pull request merged**
