### PR TITLE
Added risk labels to those displayed on deploy

### PR DESCRIPTION
**Pull request by orangejenny**
https://github.com/dimagi/commcare-hq/pull/28716#issuecomment-718805666

##### ENVIRONMENTS AFFECTED
None

### CODE REVIEW

**Review by esoergel — APPROVED** [review]
Looks good to me.

I agree with Daniel that it's easy for this output to get overwhelming (and therefore ignored), so that's good to keep in mind.  You should also feel free to take liberties with this code as you like without fear of offense - there are some variables that could be renamed and some stuff restructured.

**Comment by esoergel** [comment]
Guessing you've already figured this out, but for testing on example commit ranges, you can run
```ipython
>>> DeployDiff(_get_github(), old_commit, new_commit).warn_of_migrations()
...
```

**Comment by orangejenny** [comment]
@millerdev @esoergel Thanks for the feedback. Thinking it over, I'm leaning towards closing this. I agree that system health should always monitored post-deploy, and that lengthly output gets overwhelming and ignored. The main point of the risk labels is to change behavior *before* deploy, and if that's successful there's nothing for the deployer to worry about.

**Comment by esoergel** [comment]
As you see fit.  We _do_ show all PRs being deployed anyways, so another possibility would be to tweak that display to call attention to notable PRs, for instance by using different colors for different tags, highlighting notable rows, or if PR order doesn't matter, splitting the PR list into groups by "severest" tag.

**Comment by orangejenny** [comment]
Closing - although I did try out and enjoy the new `preview_deploy` command spawned by this conversation.

**Pull request closed without merging**
