### PR TITLE
Offboard jroth

### PR DESCRIPTION
**Pull request by gbova**
Remove jrtoh from public keys

### CODE REVIEW

**Comment by proteusvacuum** [comment]
I think we also need to remove this file: https://github.com/dimagi/commcare-cloud/blob/7d0a2e092519a33f738f39280d69a6428ecd8b02/environments/_authorized_keys/jroth.pub

**Comment by gbova** [comment]
`jroth.pub` deleted

**Comment by proteusvacuum** [comment]
I'm assuming you also ran the required `commcare-cloud` commands on all envs?

**Comment by gbova** [comment]
@proteusvacuum I thought those were to be run after this PR was merged (so it's next on my to-do list). Am I supposed to run those before merging?

**Comment by proteusvacuum** [comment]
@gbova :+1: you can do it either before or after, actually. (you can use `--branch` in `commcare-cloud` to run code from a specific branch that isn't master).

**Pull request merged**
