### PR TITLE
Add ability to set maxmemory-policy=allkeys-lru and other redis params in Elasticache

### PR DESCRIPTION
**Pull request by dannyroberts**
https://dimagi-dev.atlassian.net/browse/SAAS-14659

##### Environments Affected
staging materially (india, production superficially by replacing the default parameter group with a custom parameter group that inherits all the same defaults with no changes)

### CODE REVIEW

**Comment by dannyroberts** [comment]
This has been applied, with great success, on staging

**Review by millerdev — APPROVED** [review]

**Comment by dannyroberts** [comment]
(merged master to get the flake8 fix.)

**Comment by dannyroberts** [comment]
```
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:8:1: F401 'clint.textui.puts' imported but unused
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:9:1: F401 'commcare_cloud.colors.color_warning' imported but unused
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:19:116: E501 line too long (119 > 115 characters)
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:219:116: E501 line too long (127 > 115 characters)
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:222:1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:230:5: E301 expected 1 blank line, found 0
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:236:116: E501 line too long (132 > 115 characters)
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:239:1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:247:1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:265:1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:274:74: W291 trailing whitespace
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:277:66: W291 trailing whitespace
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:2[78](https://github.com/dimagi/commcare-cloud/actions/runs/5391230826/jobs/9787751332#step:4:79):67: W291 trailing whitespace
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:2[80](https://github.com/dimagi/commcare-cloud/actions/runs/5391230826/jobs/9787751332#step:4:81):1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:2[87](https://github.com/dimagi/commcare-cloud/actions/runs/5391230826/jobs/9787751332#step:4:88):1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:299:1: E302 expected 2 blank lines, found 1
/github/workspace/src/commcare_cloud/environment/schemas/terraform.py:304:1: E302 expected 2 blank lines, found 1
```

**Comment by dannyroberts** [comment]
Only new commits since last approval are merging in master, so I'm good to go

**Pull request merged**
