### PR TITLE
Switch to using local couchdb2 for production commcarehq db!

### PR DESCRIPTION
**Pull request by dannyroberts**
This puts us entirely on local couchdb2 and entirely off cloudant.

### CODE REVIEW

**Comment by dannyroberts** [comment]
It's hard to say, but I think so. The massive reindex is certainly negatively affecting performance this weekend, but that won't be around at nearly this level in steady state of course; and currently all writes to cloudant are being replicated to the local db. So I'd say based on these two things it can almost certainly handle the indexer load, and the write load, so the only totally untested thing is the read load. Overall though, I think we're on about the same level of resources that we have on cloudant. The cluster in AWS is at 32GB RAM / 16 vCPU / 7.5 TB disk / 15000 IOPS to data disk, times 3 nodes, with a full copy of the db on each node. Perhaps the easiest change to make if the flip does cause massive issues is to reduce the number of replicas from 3 to 2, which should reduce write load by a third.

**Comment by millerdev** [comment]
🎉

**Comment by snopoke** [comment]
Thanks @dannyroberts. Fine to proceed from me, just wanted to check that we'd at least thought about it and were reasonably confident in proceeding.

**Comment by dannyroberts** [comment]
Just noting that this is delayed for now as it's going to take some creativity and time before we're able to reindex the commcarehq db

**Comment by dannyroberts** [comment]
OK we're ready to go!

**Pull request merged**
