### PR TITLE
Add documentation for #1791

### PR DESCRIPTION
**Pull request by emord**
Tried to give roughly the same amount of info as https://github.com/dimagi/commcare-cloud/pull/1907

### CODE REVIEW

**Comment by snopoke** [comment]
Thanks.  One quick question, would it be a problem if code deploy continued to happen without running this command?

**Comment by emord** [comment]
If you code deploy from master before running this command then celery workers & formplayer would be down. (other services should have already been moved) so most things should continue working, but the `check_services` would indicate it being down.

**Comment by snopoke** [comment]
I think that's something that's important to highlight in the changelog - I'd tried to include that with the 'dependant commcare version'  but in this case that won't help. Maybe we should add another field like `Affects CommCare deploy` or something?

**Comment by emord** [comment]
I added a note about this in the details. It wasn't clear how prominent to make it. If this were a versioned utilitity I would say we could change the major version number, but not clear to me how to make a note of it when it's always expected to run from master

**Pull request merged**
