### PR TITLE
add pillow3 to prod

### PR DESCRIPTION
**Pull request by emord**
added a new server to take care of the really large backlog in case processing

buddies @mkangia @millerdev

### CODE REVIEW

**Comment by mkangia** [comment]
Thanks @emord 
Are the steps taken to add a new pillow machine listed on confluence somewhere, i guess they must be there but in different pages? But steps like
1. Provision a new machine -> link to page
2. Add to inventory, known hosts etc?
3. Ansible deploy new machine
4. Setup pillows etc etc
(^ not intended to be correct but just for example)

**Comment by emord** [comment]
@mkangia https://confluence.dimagi.com/display/internal/How+to+set+up+a+New+Rackspace+Machine

**Comment by mkangia** [comment]
@emord
What i meant was that if there is a doc to add a "pillow" machine. I understand that link would be the link for the first step or first couple of steps i mentioned earlier. But would be helpful to know steps to be taken for a pillow machine after adding the machine.

**Comment by emord** [comment]
ansible deploying sets up the processes as defined in `app-process.yml` 

I'm not exactly sure what documentation you're looking for. It could be:

a) How do I know when to add a pillow server
b) How do I decide what pillows to put on what server
c) What does the app-processes configuration mean
d)

**Pull request merged**
