### PR TITLE
add CASE_ES_DROP_FORM_FIELDS to settings

### PR DESCRIPTION
**Pull request by snopoke**
Ref https://github.com/dimagi/commcare-hq/pull/24914

### CODE REVIEW

**Comment by snopoke** [comment]
rolled out to ICDS

**Comment by sravfeyn** [comment]
Hey @snopoke Have we actively cleaned up these two fields for old docs on ES on ICDS? I was going through the documents and found most of them with non-empty values for these two fields.

**Comment by snopoke** [comment]
no we haven't

**Comment by sravfeyn** [comment]
Cleaning those fields could reduce the index size, right? Is it not worth?

**Comment by sravfeyn** [comment]
I have tested on India and ICDS by estimating size of around 10k cases with and without those properties, and there is around 12-15% of size reduction with this.

**Pull request merged**
