### PR TITLE
Double XForm pillows on ICDS

### PR DESCRIPTION
**Pull request by emord**
##### SUMMARY
Doubling XForm -> ES and UCR pillows

##### ENVIRONMENTS AFFECTED
icds

##### ISSUE TYPE
- Change Pull Request

##### COMPONENT NAME
pillow

##### ADDITIONAL INFORMATION
This is to test out how the system response. Will also need to increase the number of form partitions as documented here https://commcare-hq.readthedocs.io/pillows.html#parallel-processors

### CODE REVIEW

**Comment by emord** [comment]
I had this deployed temporarily today to see its effects on  the queue. It did not quite double the rate of processig for form UCRs, but it was around 1.75x (check 18:45 - 19:20 UTC). I reverted this (so the current status is on master) I want to be able to figure out the results of my HQ PR on the queue during peak load in isolation. Will follow up tomorrow after taking note of metrics

**Comment by emord** [comment]
This shouldn't be necessary anymore

**Comment by snopoke** [comment]
rolling this PR out reverted these changes: https://github.com/dimagi/commcare-cloud/pull/3013

**Comment by emord** [comment]
@snopoke Do you mean that rolling out #3013 reverted #2961 (this PR) changes? I think that's fine as @calellowitz only re-deployed this last night as a temporary measure

**Comment by snopoke** [comment]
@emord yes that's what I mean

**Pull request closed without merging**
