### PR TITLE
upgrading ansible to 4.2.0

### PR DESCRIPTION
**Pull request by prem-fissionhq**
https://dimagi-dev.atlassian.net/browse/SAAS-12902
##### ENVIRONMENTS AFFECTED

All.

### CODE REVIEW

**Comment by prem-fissionhq** [comment]
[PR#5306](https://github.com/dimagi/commcare-cloud/pull/5306)

**Comment by proteusvacuum** [comment]
@dannyroberts what's the upgrade process? I think as long as this is clearly mentioned, and if the monolith installation tests pass without any modification then this should be fine.

**Comment by dannyroberts** [comment]
@prem-fissionhq do you know how to run the monolith tests (and is that what you were running to test this in the first place?)

@proteusvacuum also raises a good point about the upgrade. Normally I'd say this is an update that happens fairly transparently if you're using the control machine update script regularly, since that installs all the up to date dependencies including this one. However I think I remember experiencing that to upgrade from ansible 2.x to 4.x, you actually have to **manually uninstall ansible** first before it goes through. If that's true, then can you add a changelog entry to this PR that basically just says the next time you use commcare-cloud, first run `pip uninstall ansible` and then run the command to update everything?

**Comment by prem-fissionhq** [comment]
@dannyroberts @proteusvacuum I have tested this branch in the monolith environment execution via AWX and it worked as expected. 
```
Job #3364 'commcare install' successful: http://monolith-install-awx.commcarehq.org/#/jobs/playbook/3364
[6:31](https://dimagi.slack.com/archives/C028N38MG7M/p1654088496733539)
Workflow Job #3350 'monolith-workflow' successful: http://monolith-install-awx.commcarehq.org/#/workflows/3350
[6:31](https://dimagi.slack.com/archives/C028N38MG7M/p1654088497692819)
Job #3367 'ec2_terminate' successful: http://monolith-install-awx.commcarehq.org/#/jobs/playbook/3367
```

**Comment by prem-fissionhq** [comment]
ChangeLog PR https://github.com/dimagi/commcare-cloud/pull/5318

**Comment by prem-fissionhq** [comment]
Merged this PR into #5326 https://github.com/dimagi/commcare-cloud/pull/5326

**Pull request closed without merging**
