### PR TITLE
Addition of 2 pillows

### PR DESCRIPTION
**Pull request by NitigyaS**
@snopoke what should I put in the app-processes.yml

### CODE REVIEW

**Comment by snopoke** [comment]
@emord can you fill in the processes you want to run on these 2?

**Comment by emord** [comment]
Split up the case to elasticsearch pillow to 36. We're ok right on all pillows but this will allow better processing when we finish up the case reindex work

**Comment by emord** [comment]
Looks like these weren't deployed to (and they aren't in the pillowtop group):

```
jemord@pillow10:~$ ls /home/cchq
datadog
```

was this intentional?

**Comment by NitigyaS** [comment]
Sorry for missing it. Added in https://github.com/dimagi/commcare-cloud/pull/1896.

**Pull request merged**
