### PR TITLE
Adding  formplayer1 to production environment

### PR DESCRIPTION
**Pull request by sanjay2916**
Adding new formplayer server to Production environment

### CODE REVIEW

**Comment by dannyroberts** [comment]
Yup, this is right. Go ahead and run `cchq production terraform apply` to create the machines, `cchq production aws-fill-inventory` to update inventory.ini, and `cchq production update-local-known-hosts --limit formplayer1` to update the `known_hosts` file, and commit those changes as well. You'll have to do that for the tests on this PR to pass anyway

**Comment by dannyroberts** [comment]
`manage-commcare-cloud test-environments` passes locally. Merging to get into today's deploy

**Comment by nickpell** [comment]
Did this break tests?

See: https://travis-ci.org/dimagi/commcare-cloud/jobs/514144929

**Comment by dannyroberts** [comment]
Wow, looks like it did. Thanks @nickpell!

**Pull request merged**
