### PR TITLE
add the two new redis nodes to ICDS

### PR DESCRIPTION
**Pull request by sravfeyn**
@emord @calellowitz 
cc @snopoke 

It is possible to add redis nodes without downtime, but I will test this locally on Vagrant and then rollout on ICDS. Hold on merge please.

### CODE REVIEW

**Comment by emord** [comment]
Looks like the test failure just needs update local known hosts run.

@sravfeyn how has testing the no-downtime addition going?

**Comment by sravfeyn** [comment]
Rolled it out. Resharding took about 30 minutes and quite straightforward.

**Comment by emord** [comment]
@sravfeyn Did you have to do something manual to reshard? Could you document that in commcare-cloud so that we can do it again?

**Comment by sravfeyn** [comment]
https://github.com/dimagi/commcare-cloud/pull/2980/files

**Pull request merged**
